version: '3'
services:
  latest:
    build: ./python3.7
    image: tiangolo/uvicorn-gunicorn-fastapi:latest
  python3.6:
    build: ./python3.6
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.6
  python3.6-alpine3.8:
    build: ./python3.6-alpine3.8
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.6-alpine3.8
  python3.7:
    build: ./python3.7
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.7
  python3.7-alpine3.8:
    build: ./python3.7-alpine3.8
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.7-alpine3.8
